### ISSUE TITLE
regular site routes work ... phpunit routes not found

### ISSUE THREAD

**Issue by l0c0luke** [silexphp/Silex#1442]
upgrading to silex 2 and symfony 3 and all the rest...

routes are included at end of app.php and look something like this...

```
$app->get('/', 'queue.controller:indexAction')
    ->after(function (Request $request, Response $response, $app) {
        $response->setPublic();
        $response->setSharedMaxAge($app['cache']['s-maxage']);
    })
    ->host($app['domains']['xxx'])
    ->bind('homepage');
```

this works great in a browser, goto homepage, works fine. If I am running phpunit though... I get the following error when trying to generate a route...

`Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "homepage" as such route does not exist.`

and the test looks something like this...

```
public function testTargetingOnHomepage()
    {
        $client = $this->createClient();
        echo $this->app->url('homepage');
       .....
    }
```

i am bewildered as to why my routes are not getting added to app when being executed from phpunit.

**Comment by stof** [comment]
Can you show how you create the application in your testcase ?

**Comment by l0c0luke** [comment]
test case class has ...

`class AdTargetControllerTest extends SomeWebTestCase`

and that somewebtestcase.php looks like ...

```
<?php

namespace Someecards\SomeFramework;

use Silex\WebTestCase;
use Fixtures\UserFixture;
use Symfony\Component\BrowserKit\Client;
use Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorage;

class SomeWebTestCase extends WebTestCase
{
    public $youtubeEmbed;
    private $mockSessionDir;

    public function createApplication()
    {
        $appDir = __DIR__.'/../../..';
        $app = include "$appDir/app.php";

        $app['debug'] = true;
        $app['session.test'] = true;

        $this->mockSessionDir = $app['tmpdir']. '/mocksessions';
        $app['session.storage.test'] = function ($app) {
            return new MockFileSessionStorage($app['tmpdir']. '/mocksessions');
        };

        unset($app['exception_handler']);

        // Emails get stored in the mail "logger" ... not delivered.
        $app['mailer.logger'] = function ($app) {
            return new \Someecards\SomeFramework\MessageLogger();
        };

        // Force silex to use transport and not spooltransport
        $app['swiftmailer.use_spool'] = false;

        $app["swiftmailer.transport"] = function ($app) {
            return new \Swift_Transport_NullTransport($app['swiftmailer.transport.eventdispatcher']);
        };

        $app->extend('mailer', function ($mailer, $app) {
            $mailer->registerPlugin($app['mailer.logger']);
            return $mailer;
        });

        $this->youtubeEmbed = '<iframe width="480" height="270" src="https://www.youtube.com/embed/';
        $this->youtubeEmbed .= 'LDtHJYa6xu4?feature=oembed" frameborder="0" allowfullscreen></iframe>';

        // using Mockery since this library uses a static method for create
        $app['oembedMock'] = \Mockery::mock('alias:Embed\Embed');

        $app['oembedMock']
            ->shouldReceive('create')
            ->andReturn(
                (object) array(
                    'title' => 'Oembed title',
                    'description' => 'Oembed Description',
                    'providerName' => 'YouTube',
                    'code' => $this->youtubeEmbed,
                    'type' => 'video',
                    'author' => 'test',
                    'authorUrl' => 'test',
                    'width' => 500,
                    'height' => 500,
                    'image' => 'test',
                    'imageWidth' => 500,
                    'imageHeight' => 500
                )
            );

        $app->boot();
        return $app;
    }
```

there are other functions  here but thats the important one i believe.

phpunit bootstraps with ...

```
<?php

use Someecards\SomeFramework\TestingUtil;

// autoload libraries
require_once __DIR__.'/../thirdparty/vendor/autoload.php';
TestingUtil::init();
```

and then testingutil.php looks like ...

```
<?php

namespace Someecards\SomeFramework;

class TestingUtil
{
    public static function init()
    {
        // This if/else allows the phpunit processIsolation flag to be set to true.
        // We're not currently doing that because it slows things down three fold.
        // If you see errors about too many open connections/files you can run
        // ulimit -n 10000, try to close db connections and log files (couldn't fclose
        // these in tearDowns for some reason), or turn on processIsolation.
        if (!defined('PHPUNIT_HAS_BOOTSTRAPED')) {
            self::bootstrap();
            define('PHPUNIT_HAS_BOOTSTRAPED', true);
        }
    }

    public static function bootstrap()
    {
        $app = require __DIR__.'/../../../app.php';
        $app->boot();

        $dbOptions = $app['db.options'];
        if ($dbOptions['driver'] == 'pdo_sqlite') {
            $testdb = $dbOptions['path'];
            if (file_exists($testdb)) {
                @unlink($testdb);
            }

            $cacheDriver = $app['orm.em']->getConfiguration()->getMetadataCacheImpl();
            $cacheDriver->deleteAll();
            $cacheDriver = $app['orm.em']->getConfiguration()->getResultCacheImpl();
            $cacheDriver->deleteAll();
            $cacheDriver = $app['orm.em']->getConfiguration()->getQueryCacheImpl();
            $cacheDriver->deleteAll();

            $tool = new \Doctrine\ORM\Tools\SchemaTool($app['orm.em']);
            $classes = $app['orm.em']->getMetadataFactory()->getAllMetadata();
            $tool->createSchema($classes);

            $loader = new \Doctrine\Common\DataFixtures\Loader();
            $loader->loadFromDirectory(__DIR__ ."/../../Fixtures");
            $purger = new \Doctrine\Common\DataFixtures\Purger\ORMPurger();
            $executor = new \Doctrine\Common\DataFixtures\Executor\ORMExecutor($app['orm.em'], $purger);
            $executor->execute($loader->getFixtures());
        }

        register_shutdown_function(
            function ($app) {
                $path = $app['orm.default_cache']['path'];

                if (is_dir($path) === true) {
                    $files = new \RecursiveIteratorIterator(
                        new \RecursiveDirectoryIterator($path),
                        \RecursiveIteratorIterator::CHILD_FIRST
                    );

                    foreach ($files as $file) {
                        if (in_array($file->getBasename(), array('.', '..')) !== true) {
                            if ($file->isDir() === true) {
                                rmdir($file->getPathName());
                            } elseif (($file->isFile() === true) || ($file->isLink() === true)) {
                                unlink($file->getPathname());
                            }
                        }
                    }

                    rmdir($path);
                } elseif ((is_file($path) === true) || (is_link($path) === true)) {
                    return unlink($path);
                }
            },
            $app
        );
    }
}
```

sorry for length of this reply but i _think_ it includes the juicy bits.

**Comment by slipo** [comment]
Seems like url_generator used to flush() and now it doesn't so the tests don't have routes...

Before:
https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/UrlGeneratorServiceProvider.php#L28

Now:
https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/RoutingServiceProvider.php#L49

I believe adding a flush in there should solve this.

**Comment by slipo** [comment]
Found this relevant issue: https://github.com/silexphp/Silex/pull/862

Seems like the solution might be to leave the Silex code as is and l0c0luke can add the flush into bootstrap(). Additionally, maybe the testing docs should be updated.

**Comment by l0c0luke** [comment]
flushing fixed my problem. but i believe the mounted routes are still not working in phpunit.

**Comment by stof** [comment]
this is indeed done on purpose in https://github.com/silexphp/Silex/pull/862. Your testing code is precisely in the case where the behavior changed: generating URLs outside the handling of a request.
